<script lang="ts">
	import { goto } from '$app/navigation';
	import SearchIcon from '@lucide/svelte/icons/search';
	import FileTextIcon from '@lucide/svelte/icons/file-text';
	import HashIcon from '@lucide/svelte/icons/hash';
	import XIcon from '@lucide/svelte/icons/x';
	import { Button } from '$lib/components/ui/button/index.js';
	import * as Command from '$lib/components/ui/command/index.js';
	import { Badge } from '$lib/components/ui/badge/index.js';
	import { searchPalette } from '$lib/state/search.svelte.js';
	import type { NavItem } from '$lib/docs/types.js';

	let { navigation = [] }: { navigation?: NavItem[] } = $props();

	interface SubResult {
		title: string;
		url: string;
		excerpt: string;
	}
	interface Result {
		url: string;
		title: string;
		excerpt: string;
		subResults: SubResult[];
	}

	let query = $state('');
	let searchResults = $state<Result[]>([]);
	let searching = $state(false);

	// Facet counts from the unfiltered index — the chip lists derive from
	// these so every chip stays visible and deselectable whatever the current
	// refinement...
	let globalCategoryFilters = $state<Record<string, number>>({});
	let globalTagFilters = $state<Record<string, number>>({});
	// ...and counts refined by the current search, displayed on the chips.
	let categoryFilters = $state<Record<string, number>>({});
	let tagFilters = $state<Record<string, number>>({});
	let selectedCategory = $state<string | null>(null);
	let selectedTags = $state<string[]>([]);

	const hasActiveFilters = $derived(Boolean(selectedCategory) || selectedTags.length > 0);

	// The search runs exclusively on the static Pagefind index (generated by
	// `pnpm build`, copied to static/pagefind for the dev server). No Sanity
	// queries are involved.
	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	let pagefind: any = null;
	let indexMissing = $state(false);

	async function loadPagefind() {
		if (pagefind || indexMissing) return;
		try {
			// Dynamic import with a full URL to bypass Vite's static analysis.
			const pagefindUrl = `${window.location.origin}/pagefind/pagefind.js`;
			pagefind = await import(/* @vite-ignore */ pagefindUrl);
			await pagefind.init();
			// Preload global facet counts so the chips render before typing.
			const filters = await pagefind.filters();
			globalCategoryFilters = filters?.['Catégorie'] ?? {};
			globalTagFilters = filters?.['Tag'] ?? {};
			categoryFilters = globalCategoryFilters;
			tagFilters = globalTagFilters;
			indexMissing = false;
		} catch {
			pagefind = null;
			indexMissing = true;
		}
	}

	function activeFilters() {
		// eslint-disable-next-line @typescript-eslint/no-explicit-any
		const filters: Record<string, any> = {};
		if (selectedCategory) filters['Catégorie'] = [selectedCategory];
		// Spread, don't pass the $state proxy: Pagefind posts this object to
		// its worker, and structured clone throws DataCloneError on proxies.
		if (selectedTags.length) filters['Tag'] = { any: [...selectedTags] };
		return filters;
	}

	async function runSearch(term: string | null) {
		// A null term is a filter-only browse: Pagefind then returns every
		// page matching the active facets.
		const search = await pagefind.debouncedSearch(term, { filters: activeFilters() }, 200);
		if (search === null) return; // superseded by a newer keystroke

		// eslint-disable-next-line @typescript-eslint/no-explicit-any
		const data = await Promise.all(search.results.slice(0, 20).map((r: any) => r.data()));
		// eslint-disable-next-line @typescript-eslint/no-explicit-any
		searchResults = data.map((r: any) => ({
			url: r.url,
			title: r.meta?.title ?? r.url,
			// Word-match excerpts are meaningless without a term — show the
			// page description when browsing by facet only.
			excerpt: term === null ? (r.meta?.description ?? '') : (r.excerpt ?? ''),
			subResults:
				term === null
					? []
					: (r.sub_results ?? [])
							// eslint-disable-next-line @typescript-eslint/no-explicit-any
							.filter(
								(sub: any) => sub.title && sub.title !== r.meta?.title && sub.url?.includes('#')
							)
							.slice(0, 3)
							// eslint-disable-next-line @typescript-eslint/no-explicit-any
							.map((sub: any) => ({ title: sub.title, url: sub.url, excerpt: sub.excerpt ?? '' }))
		}));
		// Facet counts refined by this search.
		categoryFilters = search.filters?.['Catégorie'] ?? categoryFilters;
		tagFilters = search.filters?.['Tag'] ?? tagFilters;
		searching = false;
	}

	$effect(() => {
		const q = query;
		// Read the filter state so toggling chips re-runs the search.
		const hasFilters = Boolean(selectedCategory) || selectedTags.length > 0;

		const term = q.length >= 2 ? q : null;
		if (term === null && !hasFilters) {
			searchResults = [];
			searching = false;
			// Back to a blank palette: restore the unfiltered counts.
			categoryFilters = globalCategoryFilters;
			tagFilters = globalTagFilters;
			return;
		}

		searching = true;
		loadPagefind().then(() => {
			if (pagefind) runSearch(term);
			else searching = false;
		});
	});

	// Open/close side effects, regardless of how the palette was toggled
	// (button, ⌘K, a tag badge on a page): apply the pending tag filter and
	// warm the index on open, reset everything on close.
	$effect(() => {
		if (searchPalette.open) {
			if (searchPalette.pendingTag) {
				selectedTags = [searchPalette.pendingTag];
				searchPalette.pendingTag = null;
			}
			loadPagefind();
		} else {
			query = '';
			searchResults = [];
			selectedCategory = null;
			selectedTags = [];
			searchPalette.pendingTag = null;
		}
	});

	function toggleCategory(name: string) {
		selectedCategory = selectedCategory === name ? null : name;
	}

	function toggleTag(name: string) {
		selectedTags = selectedTags.includes(name)
			? selectedTags.filter((tag) => tag !== name)
			: [...selectedTags, name];
	}

	function clearFilters() {
		selectedCategory = null;
		selectedTags = [];
	}

	function navigate(url: string) {
		searchPalette.open = false;
		goto(url);
	}

	function handleKeydown(e: KeyboardEvent) {
		if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
			e.preventDefault();
			searchPalette.open = !searchPalette.open;
		}
	}

	// Top tags by global count — the list stays stable while refining; only
	// the displayed counts follow the current search.
	const topTags = $derived(
		Object.entries(globalTagFilters)
			.filter(([, count]) => count > 0)
			.sort((a, b) => b[1] - a[1])
			.slice(0, 8)
			.map(([name]) => [name, tagFilters[name] ?? 0] as [string, number])
	);

	// Selected tags stay visible even when the current counts drop them out
	// of the top list — otherwise a chip could vanish right after clicking it.
	const visibleTags = $derived([
		...topTags,
		...selectedTags
			.filter((tag) => !topTags.some(([name]) => name === tag))
			.map((tag) => [tag, tagFilters[tag] ?? 0] as [string, number])
	]);
</script>

<svelte:window onkeydown={handleKeydown} />

<Button
	variant="outline"
	class="text-muted-foreground relative h-8 w-full justify-start rounded-md text-sm"
	onclick={() => (searchPalette.open = true)}
>
	<SearchIcon class="mr-2 size-4" />
	<span class="inline-flex">Rechercher...</span>
	<kbd
		class="bg-muted text-muted-foreground pointer-events-none ml-auto hidden h-5 items-center gap-1 rounded border px-1.5 font-mono text-[10px] font-medium select-none sm:flex"
	>
		<span class="text-xs">⌘</span>K
	</kbd>
</Button>

<Command.Dialog bind:open={searchPalette.open} shouldFilter={false}>
	<Command.Input placeholder="Rechercher dans la documentation..." bind:value={query} />

	{#if Object.keys(globalCategoryFilters).length || visibleTags.length}
		<div class="flex flex-wrap items-center gap-1.5 border-b px-3 py-2">
			{#each Object.keys(globalCategoryFilters) as name (name)}
				{@const count = categoryFilters[name] ?? 0}
				<button type="button" onclick={() => toggleCategory(name)} class="cursor-pointer">
					<Badge variant={selectedCategory === name ? 'default' : 'secondary'}>
						{name}
						{#if selectedCategory === name}
							<XIcon class="size-3" />
						{:else}
							<span class="opacity-60">&nbsp;{count}</span>
						{/if}
					</Badge>
				</button>
			{/each}
			{#if visibleTags.length}
				<span class="bg-border mx-1 h-4 w-px"></span>
				{#each visibleTags as [name, count] (name)}
					{#if count > 0}
						<button type="button" onclick={() => toggleTag(name)} class="cursor-pointer">
							<Badge variant={selectedTags.includes(name) ? 'default' : 'outline'}>
								{name}
								{#if selectedTags.includes(name)}
									<XIcon class="size-3" />
								{:else}
									<span class="opacity-60">&nbsp;{count}</span>
								{/if}
							</Badge>
						</button>
					{/if}
				{/each}
			{/if}
		</div>
	{/if}

	<Command.List>
		<Command.Empty>
			{#if indexMissing}
				Index de recherche absent — lancez <code class="font-mono text-xs">pnpm build</code> pour le générer.
			{:else if searching}
				Recherche...
			{:else if query.length > 0 || hasActiveFilters}
				<div class="flex flex-col items-center gap-3">
					<span>Aucun résultat{hasActiveFilters ? ' avec ces filtres' : ''}.</span>
					{#if hasActiveFilters}
						<Button variant="outline" size="sm" onclick={clearFilters}>Effacer les filtres</Button>
					{/if}
				</div>
			{:else}
				Tapez pour rechercher...
			{/if}
		</Command.Empty>

		{#if searchResults.length > 0}
			<Command.Group heading="Résultats">
				{#each searchResults as result (result.url)}
					<Command.Item value={result.url} onSelect={() => navigate(result.url)}>
						<FileTextIcon class="shrink-0" />
						<div class="flex min-w-0 flex-col gap-0.5 overflow-hidden">
							<span class="truncate font-medium">{result.title}</span>
							{#if result.excerpt}
								<span class="text-muted-foreground truncate text-xs">
									{@html result.excerpt}
								</span>
							{/if}
						</div>
					</Command.Item>
					{#each result.subResults as sub (sub.url)}
						<Command.Item value={sub.url} onSelect={() => navigate(sub.url)} class="ps-8">
							<HashIcon class="size-3.5 shrink-0 opacity-60" />
							<div class="flex min-w-0 flex-col gap-0.5 overflow-hidden">
								<span class="truncate text-sm">{sub.title}</span>
								{#if sub.excerpt}
									<span class="text-muted-foreground truncate text-xs">
										{@html sub.excerpt}
									</span>
								{/if}
							</div>
						</Command.Item>
					{/each}
				{/each}
			</Command.Group>
		{:else if !query && !hasActiveFilters}
			{#each navigation as section (section.title)}
				<Command.Group heading={section.title}>
					{#each section.items ?? [] as item (item.href ?? item.title)}
						{#if item.href}
							<Command.Item value={item.href} onSelect={() => navigate(item.href ?? '')}>
								<FileTextIcon />
								<span>{item.title}</span>
							</Command.Item>
						{/if}
					{/each}
				</Command.Group>
			{/each}
		{/if}
	</Command.List>
</Command.Dialog>
